from flask_restx import fields


model_all = {
           		"brand"                : fields.String(required = True, 
													description="Brand of the car", 
													help="Brand cannot be blank."),
				"year"                 : fields.Integer(required = True, 
													description="Year of release of the car", 
													help="Year cannot be blank."),
				"kilometers_driven"    : fields.Integer(required = True, 
													description="Number of kilometers driven by the car", 
													help="Kilometers_driven cannot be blank."),
				"owner_type"           : fields.String(required = True, 
													description="The type of the actual owner of the car", 
													help="Owner_type cannot be blank."),
				"fuel_type"            : fields.String(required = True, 
													description="The type of the fuel of the car", 
													help="Fuel_type cannot be blank."),
				"transmission"         : fields.String(required = True, 
													description="Transmission of the car", 
													help="Transmission cannot be blank."),
				"mileage"              : fields.Float(required = True, 
													description="Mileage of the car", 
													help="Mileage cannot be blank."),
				"engine"               : fields.Integer(required = True, 
													description="Engine of the car", 
													help="Engine cannot be blank."),
				"power"                : fields.Float(required = True, 
													description="Power of the car", 
													help="Power cannot be blank."),
				"seats"                : fields.Integer(required = True, 
													description="Number of seats of the car", 
													help="Seats cannot be blank."),
				"new_price"            : fields.Float(required = True, 
													description="Price of a new car", 
													help="Price cannot be blank."),
            }